services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=roombooker
      - POSTGRES_PASSWORD=58235718Vi!
      - POSTGRES_DB=roombooker
    ports:
      - 5433:5432
    networks:
      - app-networks
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=db
      - DB_PORT=5432
      - DB_DATABASE=roombooker
      - DB_USER=roombooker
      - DB_PASSWORD=58235718Vi!
    networks:
      - app-networks

networks:
  app-networks: